import type { ArticleText } from "../types"
import { dl, h, list, note, p, steps, table, tip, warn } from "../blocks"

export default {
  "customers-and-vendors": {
    title: "Customers and vendors",
    summary: "Maintain the buyers and suppliers on your documents, with the registration type that decides their VAT treatment.",
    keywords: ["customer", "vendor", "supplier", "buyer", "party", "bin", "nid", "foreign", "non-registered", "deactivate", "credit limit", "receivable", "payable"],
    body: [
      h("Registration type matters"),
      table(["Type", "Meaning", "VAT effect"],
        ["**Local**", "VAT-registered in Bangladesh (has a BIN)", "Standard treatment; input credit on purchases"],
        ["**Foreign**", "Outside Bangladesh", "Sales are zero-rated exports; purchases are imports with TTI"],
        ["**Non-registered**", "Not VAT-registered (vendors only)", "No input tax credit on purchases"],
      ),
      p("Customers must be Local or Foreign. The type can't change once documents exist, because it decides their VAT treatment."),
      h("Add a customer or vendor"),
      steps(
        "Open [Customers](/master/customers) or [Vendors](/master/vendors) and click **New customer** or **New vendor**. You can also use **Add new customer** or **Add new vendor** inside a document form.",
        "Choose the **Registration type**.",
        "Enter the **Legal name** as printed on the trade licence (stored in capitals).",
        "Enter the **BIN** (13 digits, e.g. *000731906-0203*). Foreign parties need a **Foreign reference** and **Country**; non-registered vendors can give the owner's **NID**.",
        "Add contact person, mobile, email and **Address**. For customers, the address is the default delivery address on invoices.",
        "Save.",
      ),
      h("Day-to-day"),
      list(
        "The list shows turnover, receivable or payable, and the last document. Views include *Top by turnover*, *With receivable* and *Export customers* (or *Import vendors*).",
        "Open a party to see their documents, or click **View invoices** / **View purchases**.",
        "A party with documents can't be deleted. **Deactivate** it: it disappears from pickers on new documents and its history stays. **Reactivate** any time.",
        "A party without documents can be deleted, with **Undo** right after.",
      ),
      tip("BINs are validated as you type. A wrong BIN on a 6.3 invoice is one of the most common audit findings."),
    ],
  },

  "users-and-roles": {
    title: "Managing users (administrators)",
    summary: "Invite users, assign roles, reset passwords and deactivate accounts. Includes the permissions matrix.",
    keywords: ["user", "users", "invite", "role", "permission", "reset password", "deactivate", "admin", "administrator", "temporary password", "access"],
    body: [
      h("Invite a user"),
      steps(
        "Open [Users & roles](/master/users) and click **Invite user**.",
        "Enter **Full name**, **Username** (used to sign in; can't be changed later), **Designation**, **Email**, **Mobile** and **Department / branch**.",
        "Choose the **Role**. The hint under each role explains what it allows.",
        "Click **Invite**. A **temporary password** is shown **once**. Copy it and give it to the user; they must choose their own password at the first sign-in.",
      ),
      h("Change, reset or deactivate"),
      list(
        "**Edit** changes name, contact details and role.",
        "**Reset password** generates a new one-time password and ends the user's current sessions.",
        "**Deactivate** signs the user out immediately and blocks sign-in. Their documents and audit history stay unchanged. **Activate** reverses it.",
      ),
      warn("You can't change your own role or deactivate yourself; ask another administrator. At least one active administrator is always required."),
      h("Permissions matrix"),
      p("The **Roles & permissions** tab shows exactly what each role may do:"),
      table(["Permission", "Admin", "Approver", "Operator", "Viewer"],
        ["Create documents", "✓", "✓", "✓", "–"],
        ["Edit drafts", "✓", "✓", "✓", "–"],
        ["Delete drafts", "✓", "✓", "✓", "–"],
        ["Approve documents", "✓", "✓", "–", "–"],
        ["Cancel approved documents", "✓", "✓", "–", "–"],
        ["Edit customers, vendors and items", "✓", "✓", "–", "–"],
        ["Manage users", "✓", "–", "–", "–"],
        ["Edit company profile and settings", "✓", "–", "–", "–"],
        ["View audit trail", "✓", "✓", "–", "✓"],
        ["Export CSV / print", "✓", "✓", "✓", "✓"],
      ),
      note("The server enforces the same rules. Hiding a button is only a convenience, not the security boundary."),
    ],
  },

  "company-and-branches": {
    title: "Company profile and branches",
    summary: "Registration details printed on every Mushak form, the owner and authorised signatory, and your branch units.",
    keywords: ["company", "company profile", "bin", "tin", "branch", "factory", "warehouse", "signatory", "owner", "vat category", "mushak 2.1", "address"],
    body: [
      h("What the profile holds"),
      dl(
        ["Organisation", "Name, **VAT category** (standard-rated, truncated / reduced rate, turnover tax or exempt), **BIN** (13 digits), **TIN** (12 digits), email, phone and **Address**. The address prints as the address of issue on Mushak 6.3. These are as registered with NBR (Mushak 2.1)."],
        ["Owner / managing director", "The registered person's head: name, designation, NID and mobile."],
        ["Authorised signatory", "Signs VAT returns and appears on printed Mushak documents."],
        ["Branch units", "Factories, warehouses, offices and sales centres. Branches with a separate BIN need their 4-digit **BIN branch code**."],
      ),
      h("Editing"),
      steps(
        "Open [Company profile](/master/company). Only administrators can edit; others see it read-only.",
        "Change the fields. The page warns about **unsaved changes**, and **Discard** reverts them.",
        "Use **Add branch** for a new unit. Branches with documents can't be removed, and at least one branch must remain.",
        "Save. The change is recorded in the audit trail.",
      ),
      tip("Branches appear in every document's *Branch* picker and decide where stock moves. Add a new warehouse here before transferring stock to it."),
    ],
  },

  "audit-log": {
    title: "The audit trail",
    summary: "An append-only record of who changed what and when, with field-by-field before/after values.",
    keywords: ["audit", "audit trail", "log", "history", "who changed", "sign in", "failed login", "security", "changes", "before after"],
    body: [
      h("What is recorded"),
      p("Every create, edit, approval, cancellation, deletion and restore of documents and master data is recorded, as are sign-ins, failed sign-ins, password changes, role changes and settings changes. The trail is **append-only**, and times are in Bangladesh time."),
      h("Finding an event"),
      list(
        "Open [Audit trail](/master/audit). Approvers, administrators and viewers have access.",
        "Search by reference, user or value, and filter by date, user, action and record type.",
        "Quick views: *Today*, *Approvals & cancellations*, *Master-data changes*, *Users & sign-ins* and *Failed sign-ins*.",
        "Open an event to see each changed field with its **before** and **after** values and the event ID. **Open record** jumps to the document, and **History of this record** shows all its events.",
      ),
      p("Every document also has a **History** tab with its own events. Users without audit access see a summary there."),
      tip("Auditors often ask *who approved this and when?* Open the document's History tab, or filter the trail by the reference number."),
    ],
  },

  "document-lifecycle": {
    title: "Document statuses and the period lock",
    summary: "Draft, Approved, Cancelled and locked: what each status means, what you can do, and what it does to stock and VAT.",
    keywords: ["status", "draft", "approved", "cancelled", "locked", "period lock", "edit", "cancel", "delete", "approve", "workflow", "lifecycle", "undo"],
    body: [
      h("The three statuses"),
      table(["Status", "Stock and VAT", "Who can do what"],
        ["**Draft**", "No effect; not in the books or the return", "Creators edit or delete; approvers approve"],
        ["**Approved**", "Stock moved; in the Mushak books and the period's return", "Approvers can cancel with a reason; nobody can edit"],
        ["**Cancelled**", "Effects reversed; kept for the audit trail", "Nothing; it stays as a record"],
      ),
      h("Why approved documents can't be edited"),
      p("An approved document may already be printed, given to a customer or counted in a return. Editing it would change history. To correct one, cancel it and issue a new one, or use a credit note, debit note or adjustment."),
      h("Cancelling"),
      steps(
        "Open the document and click **Cancel…**.",
        "Pick a common reason (wrong party, wrong quantity or price, goods returned, duplicate) or write your own.",
        "Confirm. The reason shows on the document and in its history.",
      ),
      h("The period lock"),
      p("When a period's Mushak 9.1 return is **submitted**, the period locks:"),
      list(
        "New documents can't be dated in it.",
        "Its documents can't be edited, approved or cancelled; the buttons are hidden and a banner explains why.",
        "Corrections go into the current, open period.",
      ),
      h("Deleting drafts"),
      p("Drafts can be deleted. A toast offers **Undo** for a few seconds, and document numbers are never reused."),
      note("In the accounting module, the *books closed up to* date works the same way for receipts and payments."),
    ],
  },

  "glossary": {
    title: "VAT glossary",
    summary: "Plain-language definitions of the Bangladesh VAT terms used across DiziVAT.",
    keywords: ["glossary", "terms", "definition", "meaning", "abbreviation", "vat", "sd", "bin", "tin", "vds", "at", "ait", "tti", "hs", "mushak", "nbr"],
    body: [
      dl(
        ["AT — Advance tax", "Tax collected at import stage; creditable in the return (note 30)."],
        ["AIT — Advance income tax", "Income tax collected at import; part of cost, not creditable for VAT."],
        ["Assessable value (AV)", "The customs value on which import duties are calculated."],
        ["BIN — Business Identification Number", "The 13-digit VAT registration number (e.g. 000731906-0203) printed on every tax invoice."],
        ["BoE — Bill of Entry", "The customs declaration for imported goods."],
        ["CD — Customs duty", "Duty on imports, part of the landed cost."],
        ["Credit note (Mushak 6.7)", "Document issued to a customer for returned goods; reduces output tax."],
        ["Debit note (Mushak 6.8)", "Document issued to a supplier for goods returned to them; reverses input tax credit."],
        ["Deemed export", "Local supply to an export-oriented unit against a back-to-back LC; zero-rated."],
        ["Economic code", "The government account code a treasury deposit is credited to, e.g. 1/1133/0015/0311 for VAT."],
        ["HS code", "The 8-digit Harmonized System code that decides an item's customs and VAT rates."],
        ["Input tax credit (rebate)", "VAT paid on purchases that can be deducted from output tax."],
        ["Mushak", "The Bangla word for VAT (মূসক), used as the prefix of NBR VAT forms."],
        ["Mushak 4.3", "Input–output coefficient (price) declaration for manufactured goods."],
        ["Mushak 6.3", "Tax invoice, issued for every taxable supply."],
        ["Mushak 9.1", "The monthly VAT return, due by the 15th of the following month."],
        ["NBR", "National Board of Revenue, the tax authority of Bangladesh."],
        ["Output tax", "VAT (and SD) charged on your sales."],
        ["RD — Regulatory duty", "Additional import duty on certain goods."],
        ["SD — Supplementary duty", "Duty on certain goods and services, charged on value; VAT is then charged on value + SD."],
        ["Tax period", "One calendar month for VAT purposes."],
        ["TR-6", "The treasury challan form used to deposit VAT, SD and other dues."],
        ["TTI — Total tax incidence", "All import taxes as a % of assessable value."],
        ["VDS — VAT deducted at source", "VAT withheld by certain buyers from the payment to a supplier and deposited by the buyer; evidenced by Mushak 6.6."],
        ["Zero-rated", "Taxable at 0% (e.g. exports); input tax credit is still allowed."],
      ),
    ],
  },

  "faq": {
    title: "Frequently asked questions",
    summary: "Quick answers to the questions users ask most, from missing buttons to locked periods.",
    keywords: ["faq", "question", "problem", "troubleshooting", "error", "can't", "cannot", "missing button", "why", "how do i"],
    body: [
      h("I can't see the Approve (or Edit) button"),
      p("Buttons appear only if your role allows the action and the document is in the right state. Operators can't approve; approved documents can't be edited; documents in a locked period can't change at all. See [Document statuses and the period lock](help:document-lifecycle)."),
      h("It says the tax period is locked"),
      p("That period's Mushak 9.1 has been submitted. Record the correction in the current period with a credit note, debit note or [VAT adjustment](help:vat-adjustments)."),
      h("I can't approve because stock is short"),
      p("The branch doesn't have enough quantity on the document date. Receive the goods (purchase, transfer or production batch) first, or save a draft and approve later."),
      h("Why is my purchase showing no input credit?"),
      p("The supplier may be non-registered, **Rebate** may be switched off on the line, or a purchase over ৳1,00,000 was paid in cash. See [Local and import purchases](help:local-purchases)."),
      h("The return won't submit"),
      list(
        "The period must have ended; returns can be submitted from the 1st of the next month.",
        "The **Submission date** must be set under *Edit details*.",
        "Deposits (note 58) must cover VAT payable (note 50). Deposit the shortfall by [TR-6](help:treasury-tr6).",
      ),
      h("A customer paid less because they withheld VAT"),
      p("Record their Mushak 6.6 certificate under [VDS](help:vds-certificates), sales side. It settles the difference on the invoice."),
      h("How do I print or save a form as PDF?"),
      p("Open the document and use its **Print** button (e.g. *Print Mushak 6.3*). In the print dialog, choose **Save as PDF**. Articles in this guide work the same way; see [Using this knowledge base](help:using-this-help)."),
      h("Where is Mushak 4.3?"),
      p("Under **NBR VAT › [Mushak 4.3](/vat/mushak-4-3)**. It lists every price declaration with the official form ready to print or save as PDF. Declarations are created and amended in [Bill of materials](/production/bom); see [Find and print Mushak 4.3](help:bom#sec-4)."),
      h("I was signed out"),
      p("Sessions last 12 hours (7 days with *Keep me signed in*). An administrator may also have reset your password or deactivated the account. Sign in again and you return to the same page."),
      h("Numbers show in Bangla digits"),
      p("That follows the language setting. Switch to English from the account menu or the command palette. Printed NBR forms keep their official layout either way."),
      tip("Still stuck? Ask your DiziVAT administrator. They can see the [audit trail](help:audit-log) for what happened."),
    ],
  },
} satisfies Record<string, ArticleText>
