import type { ArticleText } from "../types"
import { dl, h, list, note, p, steps, table, tip, warn } from "../blocks"

export default {
  "welcome": {
    title: "Welcome to DiziVAT",
    summary: "What DiziVAT does, how the modules fit together and how a document flows from entry to the Mushak 9.1 return.",
    keywords: ["overview", "introduction", "about", "modules", "what is", "RBS VAT", "new system"],
    body: [
      h("What DiziVAT is"),
      p("**DiziVAT** is a VAT management system for Bangladeshi manufacturers and traders. It records your sales, purchases, stock, production and payments, and turns them into the forms the National Board of Revenue (NBR) expects: Mushak 6.3 invoices, the 6.1 and 6.2 books, credit and debit notes, VDS certificates and the monthly **Mushak 9.1** return."),
      p("DiziVAT replaces the older *RBS VAT* screens. The data model is the same, so figures you already know (challan numbers, HS codes, BINs) carry over."),
      h("The modules"),
      table(["Module", "What you do there", "NBR forms"],
        ["**Sales**", "Issue tax invoices for goods and services, exports and customer returns", "6.3, 6.7"],
        ["**Purchase**", "Record local and import purchases, services, returns to suppliers and opening stock", "6.8 (input for 6.1 and 9.1)"],
        ["**Inventory**", "Maintain items and HS codes, move stock between branches, write off damage", "6.5"],
        ["**Production**", "Declare input–output coefficients, raise work orders and batches", "4.3, 6.4"],
        ["**Accounting**", "Receive and pay money, manage bank and wallet accounts, print party statements", "none"],
        ["**NBR VAT**", "Prepare and submit the return, deposit tax, handle VDS and adjustments", "9.1, TR-6, 6.6, 6.1, 6.2, 6.10"],
        ["**Master data**", "Customers, vendors, units, users, company profile and the audit trail", "none"],
      ),
      h("How a document flows"),
      steps(
        "You **create** a document such as a sales invoice. It starts as a **Draft**, which does not affect stock or VAT.",
        "An approver checks it and clicks **Approve**. Stock moves and the document enters the Mushak books and the current period's return.",
        "If something is wrong after approval, you **cancel** the document with a reason and issue a correct one. Approved documents are never edited.",
        "At month end you open [Return (Mushak 9.1)](/vat/return-9-1), deposit the tax with a [TR-6 challan](/vat/tr-6) and **submit**. The period then locks.",
      ),
      tip("Read [Document statuses and the period lock](help:document-lifecycle) once. It explains nearly every *why can't I edit this?* question."),
      h("The dashboard"),
      p("The [Dashboard](/) shows the current VAT period at a glance:"),
      list(
        "sales, output VAT, input VAT (rebate) and net VAT payable;",
        "the compliance calendar with the treasury deposit and 9.1 deadlines;",
        "top customers, low-stock items and recent invoices;",
        "documents waiting for approval.",
      ),
      p("The status bar at the bottom always shows your BIN, the open VAT period and the days left until the return is due."),
      h("About this demo"),
      note("The public demo runs on realistic **mock data** for a fictitious company (RUPSHA FLEXIPACK LTD). Nothing you do there reaches NBR. Changes are kept only in your browser and can be reset at any time."),
    ],
  },

  "sign-in-and-roles": {
    title: "Signing in, roles and your password",
    summary: "Sign in securely, understand what your role allows, change your password and know when you'll be signed out.",
    keywords: ["login", "log in", "sign in", "password", "role", "permission", "locked", "session", "logout", "approver", "operator", "viewer", "admin"],
    body: [
      h("Signing in"),
      steps(
        "Open DiziVAT and enter your **Username** and **Password**.",
        "Tick **Keep me signed in for 7 days** only on a device you alone use. Otherwise your session ends after 12 hours.",
        "Click **Sign in**. You return to the page you were trying to open.",
      ),
      p("A warning appears if **Caps Lock** is on. After **5 wrong passwords** the account is locked for one minute, and the sign-in page counts down."),
      warn("DiziVAT staff will never ask for your password. If you forget it, ask your administrator to **reset** it. You will receive a one-time password and must choose a new one at your next sign-in."),
      h("Roles"),
      p("Every user has exactly one role. Buttons you are not allowed to use are hidden, and the server rejects the action as well."),
      table(["Role", "Typical user", "Can do"],
        ["**Administrator**", "IT / system owner", "Everything, including users, company profile, VAT and production settings"],
        ["**Approver**", "Accounts lead, shift-in-charge", "Create, **approve** and **cancel** documents; edit master data; view the audit trail"],
        ["**Operator**", "Store officer, data entry", "Create and edit **drafts**; cannot approve or cancel"],
        ["**Viewer**", "VAT consultant, auditor", "Read everything, export CSV, print and view the audit trail"],
      ),
      tip("As an operator you can still complete a whole invoice. Save it as a draft and an approver will see it under **Awaiting approval**."),
      h("Changing your password"),
      steps(
        "Open the account menu (your initials, top right) and choose **Change password**.",
        "Enter your current password and the new one twice. Passwords need 8–64 characters with at least one letter and one digit, and must differ from your username.",
        "Click **Change password**. Other devices signed in to your account are signed out.",
      ),
      h("When you are signed out"),
      list(
        "After 12 hours, or 7 days with *Keep me signed in*.",
        "When an administrator deactivates your account or resets your password.",
        "When you choose **Sign out** from the account menu.",
      ),
      p("If your session ends while you work, DiziVAT asks you to sign in again and brings you back to the same page."),
      note("In the demo, the sign-in page lists demo accounts for each role. Click one to fill it in; the password is `demo1234`."),
    ],
  },

  "navigation": {
    title: "Finding your way around",
    summary: "Sidebar, module tabs, the ⌘K command palette, the New menu, notifications and keyboard shortcuts.",
    keywords: ["menu", "sidebar", "search", "command palette", "ctrl k", "shortcut", "keyboard", "notification", "breadcrumb", "mobile"],
    body: [
      h("Sidebar and module tabs"),
      p("The **sidebar** on the left lists the modules. Click a module to expand its pages. Press {{Ctrl+B}} (or {{⌘+B}} on a Mac) to collapse it to icons and gain space. On phones, the bottom bar holds the most used modules; **More** opens the full menu."),
      p("Inside a module, the **tabs** under the top bar switch between its pages, for example *Sales invoices*, *Service sales*, *Credit notes* and *Export sales*. The breadcrumb above each page title shows where you are."),
      h("Search and the command palette"),
      p("Press {{Ctrl+K}} or {{/}} anywhere, or click the search box in the top bar, to open the **command palette**. From there you can:"),
      list(
        "search documents and records: invoice or challan numbers, customers, vendors and items (type at least two characters);",
        "jump to any page you have access to, including this knowledge base;",
        "start a new document;",
        "switch between light and dark theme, or between English and Bangla.",
      ),
      p("Recently opened pages appear at the top when the search is empty."),
      h("The New menu and notifications"),
      p("**New** in the top bar creates the documents your role may create. Press {{N}} inside a module to start a new record of that module."),
      p("The **bell** shows documents waiting for approval, approvals and cancellations by colleagues, low-stock alerts and upcoming NBR deadlines. **Mark all read** clears the badge."),
      h("Help"),
      p("The **?** button in the top bar opens the help menu:"),
      list(
        "**Help for this page** opens the article for the screen you are on;",
        "**Knowledge base** opens this guide;",
        "**Keyboard shortcuts** shows every shortcut.",
      ),
      h("Keyboard shortcuts"),
      table(["Keys", "Action"],
        ["{{Ctrl+K}} or {{/}}", "Open the command palette"],
        ["{{?}}", "Show keyboard shortcuts"],
        ["{{Ctrl+B}}", "Collapse or expand the sidebar"],
        ["{{G}} then {{D}}", "Go to the dashboard"],
        ["{{G}} then {{S}}", "Go to sales invoices"],
        ["{{G}} then {{P}}", "Go to purchases"],
        ["{{G}} then {{I}}", "Go to items"],
        ["{{N}}", "New record in the current module"],
        ["{{Ctrl+Enter}}", "Save & approve in document forms (when your role allows)"],
        ["{{Esc}}", "Close a dialog, sheet or menu"],
      ),
      tip("Shortcuts are ignored while you type in a field, so {{N}} in a text box is just the letter *n*."),
    ],
  },

  "lists-and-preferences": {
    title: "Working with lists and your preferences",
    summary: "Search, filter, sort and export any list; save views; set theme, colours, density, text size and language.",
    keywords: ["filter", "sort", "columns", "saved view", "csv", "export", "excel", "theme", "dark mode", "language", "bangla", "density", "font size", "pagination"],
    body: [
      h("Searching and filtering"),
      p("Every list (invoices, purchases, items, and so on) works the same way:"),
      list(
        "The **search box** matches numbers, names, BINs and other text shown in the list.",
        "**Date range** has presets: *Today*, *Last 7 days*, *This VAT period*, *Last VAT period*, *This quarter*, *This fiscal year* and *Last fiscal year*. Fiscal years run from July to June.",
        "**Filter buttons** such as *Status*, *Customer* or *Branch* show counts next to each option. Choose several options to widen the filter.",
        "Active filters appear as chips. Remove one with its **×**, or all of them with **Clear all**.",
      ),
      p("The summary line above the table (count, totals, VAT) always reflects the current filters."),
      h("Sorting, columns and pages"),
      list(
        "Click a column header to sort; click again to reverse the order.",
        "**Columns** lets you hide columns and change their order with *Move up* and *Move down*. **Reset** restores the default. DiziVAT remembers your layout per list on this device.",
        "Choose 10–100 **rows per page** at the bottom of the list.",
      ),
      h("Views and sharing"),
      p("**Views** offers quick views such as *Awaiting approval*, *This VAT period* or *Unpaid & partly paid*. To keep your own combination of filters, sort and search, choose **Save current view** and give it a name. Saved views are stored with your account."),
      p("Filters live in the page address, so **Copy link** shares exactly what you see with a colleague who has access."),
      h("Selecting rows and exporting"),
      steps(
        "Tick rows (or the header box to select the whole page). A bar shows the selection count and bulk actions, for example **Approve** for drafts if you are an approver.",
        "Click **Export CSV** to download the whole filtered list, not just the current page. Where offered, **Export selected** downloads only the ticked rows.",
        "Open the file in Excel or LibreOffice. Amounts are plain numbers, so totals calculate correctly.",
      ),
      h("Preferences"),
      p("Open the account menu (your initials, top right) to set:"),
      dl(
        ["Theme", "Light, Dark or System (follows your device)."],
        ["Accent colour", "Blue, Emerald, Violet or Orange, for buttons and highlights."],
        ["Table density", "Compact, Cozy or Comfortable row height."],
        ["Text size", "Default (100%), Large (112%) or Extra large (125%)."],
        ["Language", "English or বাংলা. Bangla also shows numbers and dates in Bangla. Printed NBR forms keep their official bilingual layout."],
      ),
      p("Preferences follow your account to any device you sign in on."),
    ],
  },

  "using-this-help": {
    title: "Using this knowledge base",
    summary: "Search the guides, open help for the screen you're on, and print, share or download any article or the whole manual.",
    keywords: ["help", "documentation", "manual", "user guide", "print", "pdf", "download", "share", "markdown", "html", "whatsapp", "email"],
    body: [
      h("Finding an article"),
      list(
        "Open the knowledge base from the **?** menu in the top bar, the **Help & documentation** link at the bottom of the sidebar, or the command palette ({{Ctrl+K}}).",
        "Type in the search box. Search looks at titles, summaries, section headings and keywords, including form numbers such as *6.3* or *9.1*, and matches English or Bangla digits.",
        "Use the topic chips to narrow the list to one module.",
        "On any screen, **? → Help for this page** opens the matching article directly.",
      ),
      p("Each article lists **On this page** (its sections), the **Screens covered** with links that open them, and **Related articles**."),
      h("Printing and saving as PDF"),
      steps(
        "Click **Print** above the article. DiziVAT prepares a clean A4 layout without menus or buttons.",
        "In the print dialog, choose a printer, or choose **Save as PDF** as the destination to get a PDF file.",
      ),
      p("**PDF** does the same and reminds you to pick *Save as PDF*. Using the browser's own PDF engine keeps Bangla text correctly shaped."),
      h("Sharing"),
      p("**Share** offers:"),
      list(
        "**Share…**: your device's share sheet (phones and some browsers);",
        "**Copy link**: the article's address. The recipient signs in to DiziVAT and lands on the article;",
        "**Email**: a new email with the title, summary and link;",
        "**WhatsApp**: a WhatsApp message with the link.",
      ),
      p("To point someone at one section, hover over its heading, click **#** and copy the address."),
      h("Downloading"),
      table(["Format", "Best for"],
        ["**PDF** (via Save as PDF)", "Printing, filing or attaching to an email"],
        ["**Web page (.html)**", "Reading offline in any browser. One self-contained file with working links"],
        ["**Markdown (.md)**", "Editing, adding to your own SOPs or a wiki, version control"],
      ),
      h("The full manual"),
      p("On the knowledge base home page, **Full manual** downloads every article in the current language as one document, with a cover page and table of contents. Use it as PDF, HTML or Markdown. **Print full manual** prints the whole guide."),
      tip("Switch the language to বাংলা first to print or download the Bangla edition."),
    ],
  },
} satisfies Record<string, ArticleText>
