import type { ArticleText } from "../types"
import { dl, h, list, note, p, steps, table, tip, warn } from "../blocks"

export default {
  "compliance-centre": {
    title: "NBR compliance centre",
    summary: "The tax period at a glance: return status, what is still to deposit, VDS to issue, and every Mushak report.",
    keywords: ["compliance", "mushak reports", "nbr", "deadline", "tax period", "calendar", "reports", "overview", "due date"],
    body: [
      h("What you see"),
      p("[Mushak reports](/vat/mushak) is the NBR compliance centre. Pick a tax period in **Tax periods** (newest first). The page then shows:"),
      list(
        "**Mushak 9.1 for the period**: due date and days left (or overdue), or the submission date and acknowledgement number once submitted.",
        "**Still to deposit**: the amount that must be paid by TR-6 before the return can be submitted, with a **Deposit (TR-6)** button that pre-fills the challan.",
        "**Draft documents** dated in the period that aren't counted yet.",
        "**Treasury deposits**: approved challans and drafts not yet counted.",
        "**VDS**: certificates you still have to issue, and certificates awaited from customers.",
      ),
      p("The main button reads **Prepare return**, **Continue return** or **View return**, depending on the period's status."),
      h("Every Mushak report in one place"),
      table(["Form", "What it is", "Where it lives"],
        ["4.3", "Input–output coefficient", "[Bill of materials](/production/bom)"],
        ["6.1", "Purchase book", "[Purchase book (6.1)](/vat/mushak-6-1)"],
        ["6.2", "Sales book", "[Sales book (6.2)](/vat/mushak-6-2)"],
        ["6.3", "Tax invoice", "Printed from each [sales invoice](/sales)"],
        ["6.4", "Contract-production challan", "Printed from each contractual [batch](/production/batches)"],
        ["6.5", "Transfer challan", "[Stock transfers](/inventory/transfers)"],
        ["6.6", "VDS certificate", "[VDS](/vat/vds)"],
        ["6.7", "Credit note", "[Credit notes](/sales/credit-notes)"],
        ["6.8", "Debit note", "[Debit notes](/purchases/debit-notes)"],
        ["6.10", "Purchases & sales over ৳2 lakh", "[Mushak 6.10](/vat/mushak-6-10)"],
        ["9.1", "VAT return with sub-forms", "[Return (Mushak 9.1)](/vat/return-9-1)"],
        ["TR-6", "Treasury challan", "[Treasury challan (TR-6)](/vat/tr-6)"],
      ),
      tip("The monthly routine: clear drafts → check VDS → deposit by TR-6 → submit the 9.1 by the **15th** of the following month."),
    ],
  },

  "vat-return-9-1": {
    title: "Preparing and submitting the Mushak 9.1 return",
    summary: "How DiziVAT builds the monthly return from approved documents, how to fill the manual notes, deposit and submit, and what the period lock means.",
    keywords: ["9.1", "mushak 9.1", "vat return", "return", "submit", "period lock", "locked", "net payable", "closing balance", "sub-form", "note 58", "interest", "penalty", "refund", "amended return", "late return", "deadline"],
    body: [
      h("How the return is built"),
      p("DiziVAT computes the return live from **approved** documents dated in the tax period. Every note can be drilled down to its source documents."),
      table(["Part", "Notes", "Comes from"],
        ["3. Supplies (output tax)", "1–9", "Sales invoices: export (1), deemed export (2), exempt/0% (3), 15% (4), other rates (7)"],
        ["4. Purchases (input tax)", "10–23", "Local purchases and imports by rate and rebate status; unregistered suppliers (20)"],
        ["5. Increasing adjustments", "24–28", "VDS you withheld (24), cash purchases over ৳1 lakh (25), debit notes (26), VAT adjustments (27)"],
        ["6. Decreasing adjustments", "29–33", "VDS withheld from you (29), AT on imports (30), credit notes (31), VAT adjustments (32)"],
        ["7. Net tax", "34–53", "Formulas, manual interest/penalty/surcharges (41–49) and last period's closing balance (52–53)"],
        ["9. Deposits", "58–64", "Approved TR-6 challans by economic code"],
        ["10. Closing balance", "65–66", "Deposits less payable; carried to the next period"],
      ),
      p("Key formulas: **34** net VAT = 9c − 23b + 28 − 33; **35** = 34 − (52 + 56); **50** VAT payable = 35 + 41 + 43 + 44; **65** closing balance = 58 − (50 + 67)."),
      p("[VAT settings](help:vat-settings-and-tariff) lists the source of every note."),
      h("Step by step"),
      steps(
        "Open [Return (Mushak 9.1)](/vat/return-9-1) and choose the **Tax period**. The KPIs show output tax, input tax credit, net VAT, net payable, deposited and closing balance.",
        "Approve or delete any **draft documents** dated in the period. The page warns how many are left out.",
        "Click **Start return**. Under **Edit details**, set the **Submission date**, confirm that there were economic activities, enter any Part 7 **interest, penalties and surcharges** (notes 41–49) and, if you want one, a Part 11 **refund** request.",
        "Check the notes. Click a note to open its **sub-form** listing the documents behind it.",
        "If a **shortfall** is shown, deposit the amount under the economic code given, using **Deposit (TR-6)**. Note 58 must cover note 50.",
        "When the period has ended and nothing is short, click **Submit return** and confirm **Submit and lock**.",
      ),
      warn("The return can be submitted only **after** the period ends (from the 1st of the next month) and must be submitted by the **15th**. After that it is marked *Late* and interest or penalty may apply."),
      h("The period lock"),
      p("Submitting freezes the figures. No document dated in that period can then be created, edited, approved or cancelled; DiziVAT hides those buttons and explains why. Record corrections in the **current** period with a [credit or debit note](help:credit-notes) or a [VAT adjustment](help:vat-adjustments)."),
      h("Return history"),
      p("**Return history** lists every tax period since the first return, newest first, with status (Open, Draft, Submitted or Overdue), type (Original, Amended, Full / alternative or Late) and acknowledgement number. **Print** gives the bilingual official layout."),
      note("A draft return can be deleted with **Delete draft**. This removes only the header details and manual notes; documents are not affected."),
    ],
  },

  "treasury-tr6": {
    title: "Treasury deposits (TR-6)",
    summary: "Record TR-6 challans for VAT, VDS, SD, interest, penalties and surcharges so they count in Part 9 of the return.",
    keywords: ["tr-6", "tr6", "treasury", "challan", "deposit", "a-challan", "e-payment", "economic code", "sonali bank", "note 58", "pay vat"],
    body: [
      h("Record a deposit"),
      steps(
        "Open [Treasury challan (TR-6)](/vat/tr-6) and click **New deposit**. From a return shortfall, **Deposit (TR-6)** pre-fills the head, period and amount.",
        "Choose the **Head**. DiziVAT shows its economic code, for example VAT *1/1133/0015/0311*.",
        "Choose the **Tax period**. Only periods whose return is still open are offered.",
        "Enter the **Challan no.**, **Challan date**, **Amount**, **Mode** (e-Payment (A-Challan), cheque, pay order, demand draft or cash), **Bank**, **Branch** and **District**.",
        "Optionally link **Paid from account**. That account then needs enough balance.",
        "Fill in the depositor details and the description (pre-filled as *[head] for tax period [period]*).",
        "**Save & approve**. Print the **TR Form 6** tab if you need a copy.",
      ),
      h("Heads and return notes"),
      table(["Head", "9.1 note"],
        ["VAT, VAT deducted at source, interest, penalty / fine", "58"],
        ["Supplementary duty", "59"],
        ["Excise duty", "60"],
        ["Development surcharge", "61"],
        ["ICT development surcharge", "62"],
        ["Health protection surcharge", "63"],
        ["Environment protection surcharge", "64"],
      ),
      tip("Deposit VDS you withheld under the **VAT deducted at source** head, then link the challan on each VDS certificate."),
      note("Drafts don't count. Only approved challans reach notes 58–64. A challan quoted by VDS entries can't be deleted until they are unlinked."),
    ],
  },

  "vds-certificates": {
    title: "VAT deducted at source (VDS) and Mushak 6.6",
    summary: "Withhold VAT from suppliers and issue 6.6 certificates, and record certificates received from customers who withhold from you.",
    keywords: ["vds", "vat deducted at source", "withholding", "6.6", "mushak 6.6", "certificate", "note 24", "note 29", "withhold"],
    body: [
      h("Two sides of VDS"),
      table(["", "Purchase side (we withhold)", "Sales side (customer withholds)"],
        ["When", "You pay a supplier whose supply is subject to VDS", "A VDS-entity customer pays you less the VAT"],
        ["Certificate", "You **issue** a Mushak 6.6", "You **receive** a Mushak 6.6 and record it"],
        ["Effect on due", "Supplier's payable falls by the VAT withheld", "Customer's receivable falls by the VAT withheld"],
        ["9.1 note", "Note 24 (increasing); deposit in note 58", "Note 29 (decreasing)"],
      ),
      h("Issue a certificate (purchase side)"),
      steps(
        "Open [VDS](/vat/vds). The **To issue** panel lists supplier invoices with VAT still to withhold.",
        "Click **Issue for …** on one, or **New VDS entry** and set **Side** to *Purchase (we withhold)*.",
        "Check **VAT withheld**. It can't exceed the VAT left to withhold on the invoice.",
        "Link the **Treasury challan**: a VDS-head challan of this or a later period.",
        "**Save & approve** and print the **Mushak 6.6** for the supplier.",
      ),
      h("Record a certificate (sales side)"),
      steps(
        "The **Awaiting from customers** panel lists invoices to VDS withholders without a certificate.",
        "Click **Record for …**, enter the **Certificate no.** and **date** as printed on the customer's certificate, and the amount.",
        "**Save & approve**. The invoice due falls and the amount counts in note 29.",
      ),
      warn("A VDS entry can't move to another invoice. Delete the draft and create a new one instead."),
      tip("Use the **All / Purchase / Sales** tabs to see each side separately."),
    ],
  },

  "vat-adjustments": {
    title: "VAT adjustments",
    summary: "Manual increasing and decreasing adjustments for Mushak 9.1 notes 27, 32, 38 and 39.",
    keywords: ["adjustment", "vat adjustment", "sd adjustment", "increase", "decrease", "note 27", "note 32", "note 38", "note 39", "correction"],
    body: [
      h("When to use an adjustment"),
      p("Use [VAT adjustments](/vat/adjustments) only for corrections not covered by credit notes, debit notes or VDS, for example an assessment order or a correction of a locked period. Always give the reason and reference; auditors read them."),
      table(["Kind", "9.1 note"],
        ["VAT increase", "27"],
        ["VAT decrease", "32"],
        ["SD increase", "38"],
        ["SD decrease", "39"],
      ),
      h("Record an adjustment"),
      steps(
        "Click **New adjustment** and choose the **Kind**. The form shows which note it goes to.",
        "Choose the **Tax period** (must be open) and the **Date**.",
        "Enter the **Amount**, the **Reference** (order, letter or document no.) and the **Reason**.",
        "**Save & approve**. Drafts don't count in the return.",
      ),
      note("Each approved adjustment shows as *Note n · period* in the list and appears in the matching 9.1 sub-form."),
    ],
  },

  "purchase-sales-books": {
    title: "Mushak 6.1, 6.2 and 6.10 books",
    summary: "Generate the purchase book (6.1), sales book (6.2) and the report of invoices above ৳2 lakh (6.10).",
    keywords: ["6.1", "6.2", "6.10", "mushak 6.1", "mushak 6.2", "mushak 6.10", "purchase book", "sales book", "register", "stock register", "2 lakh"],
    body: [
      h("Purchase book (6.1) and sales book (6.2)"),
      dl(
        ["Mushak 6.1 — purchase book", "Inputs bought, consumed and in hand, per item: raw materials, consumables and packing."],
        ["Mushak 6.2 — sales book", "Finished goods produced, sold and in hand, per item."],
      ),
      steps(
        "Open [Purchase book (6.1)](/vat/mushak-6-1) or [Sales book (6.2)](/vat/mushak-6-2).",
        "Select the **item** and the **From**–**To** dates.",
        "Read the book: opening balance, each movement with its document, and the closing balance.",
        "Click **Print** for the official bilingual layout, or **Open stock ledger** for the underlying movements.",
      ),
      p("The books are generated from the stock ledger, so the closing balance always equals stock on hand. Opening stock entries appear in the opening row."),
      h("Mushak 6.10"),
      p("[Mushak 6.10](/vat/mushak-6-10) lists purchase and sale invoices above **৳2,00,000** in a tax period, as required with the monthly return (rule 42(1)). Choose a **Tax period** or a custom range and print it."),
      tip("Empty sections simply say there were no invoices above the limit in the period."),
    ],
  },

  "vat-settings-and-tariff": {
    title: "VAT settings and the tariff",
    summary: "Set your VAT zone code, see the economic codes and where each 9.1 note comes from, and look up HS-code rates.",
    keywords: ["vat settings", "zone code", "economic code", "tariff", "hs code", "duty rates", "cd", "rd", "ait", "at", "tti", "note sources"],
    body: [
      h("VAT settings"),
      p("[VAT settings](/vat/settings) (administrators) holds:"),
      list(
        "The 4-digit **zone code** of your VAT commissionerate. It forms part of the economic codes on TR-6 challans.",
        "The **economic codes** for each treasury head.",
        "The **Mushak 9.1 notes** table, which shows every note and the documents or formula it comes from. Use it to answer *where does this figure come from?*",
      ),
      h("Tariff & HS codes"),
      p("[Tariff & HS codes](/vat/tariff) lists NBR customs and VAT rates by HS code, filterable by VAT rate, chapter and SD."),
      table(["Rate", "Meaning"],
        ["CD", "Customs duty"],
        ["SD", "Supplementary duty"],
        ["VAT", "Value added tax"],
        ["AIT", "Advance income tax"],
        ["RD", "Regulatory duty"],
        ["AT", "Advance tax"],
        ["TTI", "Total tax incidence, the total tax on import as a % of assessable value"],
      ),
      note("Import purchases pre-fill their duty rates from this tariff, and items check their HS code against it."),
    ],
  },
} satisfies Record<string, ArticleText>
