import type { ArticleText } from "../types"
import { h, list, note, p, steps, table, tip, warn } from "../blocks"

/** R6.3 articles: SD on exported inputs, UD amendments & BB-LC values, interest & penalties, backup restore. */
export default {
  "sd-on-exported-inputs": {
    title: "SD paid on inputs of exported goods (Mushak 9.1 note 40)",
    summary: "Take back the supplementary duty paid on imported packing and other inputs when the goods are exported within six months — one linked claim per input and export.",
    keywords: ["sd", "supplementary duty", "note 40", "export", "six months", "6 months", "polybag", "carton", "gum tape", "decreasing adjustment", "sd refund", "sd adjustment", "rmg", "packing"],
    body: [
      h("When SD can be taken back"),
      p("Supplementary duty (SD) paid when you buy or import an input — polybags, gum tape and export cartons carry SD at import — is not an input-tax credit. When the input goes into goods you **export within six months of the purchase**, the SD may be taken back as a decreasing adjustment of SD in the return: **note 40**, which reduces note 36 (net payable SD)."),
      p("DiziVAT records each claim as a VAT adjustment of kind **SD on exported inputs**, linked to the SD-paid purchase line and to the direct-export invoice the input went into. The amount is not typed: it is the SD of the purchase line, pro rata to the quantity you claim."),
      h("The six-month register"),
      p("[VAT adjustments](/vat/adjustments) opens with **SD paid on inputs — export window**: every approved purchase line that carried SD, what is already claimed, what is left and the last export date that still qualifies."),
      table(["Status", "Meaning"],
        ["Open", "Inside the window — claim against exports as they ship"],
        ["Ends soon", "Fewer than 30 days left in the window"],
        ["Lapsed", "Six months have passed — what is left can no longer be claimed"],
        ["Fully claimed", "The whole quantity is claimed"],
      ),
      h("Claiming"),
      steps(
        "In the register, click **Claim** on the purchase line (or **New adjustment** and choose *SD on exported inputs*).",
        "Pick the **export invoice** — only approved direct exports shipped between the purchase date and the end of its window are offered.",
        "Enter the **quantity** of the input used for that shipment (no more than what is still unclaimed). The amount is calculated and a reason is filled in for you.",
        "Choose the tax period (the period of the export or later) and **Save & approve**. The amount appears in note 40 of that period's return, with the claim in the note's drill-down.",
      ),
      note("Drafts reserve their quantity, so the same SD cannot be claimed twice. Approving a draft checks again that the quantity is still available."),
      warn("Keep the packing list, the EXP and the Bill of Entry with each claim: the VAT officer checks that the input really went into the export. Claims in a submitted period are locked like every other adjustment."),
      tip("Related: [VAT adjustments](help:vat-adjustments), [Mushak 9.1 return](help:vat-return-9-1), [Local purchases and imports](help:local-purchases)."),
    ],
  },
  "ud-amendments-and-bblc": {
    title: "UD amendments and back-to-back LC values",
    summary: "Record UD amendments with their reason and history, and see how much of each UD's value the back-to-back LCs opened in your favour have used.",
    keywords: ["ud", "up", "amendment", "amend", "bblc", "back to back lc", "lc value", "master lc", "export lc", "bkmea", "bgmea", "deemed export", "rmg"],
    body: [
      h("Amending a UD"),
      p("Garment orders change: a buyer adds pieces, cancels a colour, or the export LC is amended. The exporter then gets a UD amendment from BGMEA / BKMEA. In the [UD / bond register](/vat/ud-register), click the pencil on the UD, change the quantities or values and fill in the **Amendment** box."),
      list(
        "Every change of a line's quantity or value, or of the export LC value, is saved as a numbered **amendment** with its date, reason and the before → after figures.",
        "Once an invoice uses the UD, the **reason is required** and a line cannot go below the quantity already supplied.",
        "The UD's history and the audit log show who amended it and when.",
      ),
      h("Values and back-to-back LCs"),
      p("Each UD line can carry the **value** the UD permits for that input (USD), and the UD the **export LC value**. The deemed-export invoices that cite the UD carry the back-to-back LC (BB-LC) the exporter opened in your favour and its foreign-currency value. The UD view adds them up per BB-LC and compares the total with the UD values."),
      table(["State", "Meaning"],
        ["Within UD value", "BB-LCs use less than 80 % of the values on the UD"],
        ["Near the UD value", "80 % or more is used — the next BB-LC may need an amended UD"],
        ["Above the UD value", "BB-LCs exceed the UD — the exporter must amend the UD before more supplies"],
      ),
      note("Only approved invoices count; drafts are listed next to their BB-LC. A UD without values shows its BB-LCs but no percentage."),
      tip("Related: [RMG exports and UDs](help:rmg-exports-and-uds), [Exports](help:exports)."),
    ],
  },
  "interest-and-penalties": {
    title: "Late payment interest and late-return penalty",
    summary: "What a late return or late payment costs — §127 interest on unpaid VAT and SD and the late-return penalty — for any period, with a what-if calculator.",
    keywords: ["interest", "penalty", "late", "late return", "late payment", "section 127", "127", "note 41", "note 42", "note 43", "fine", "overdue", "due date"],
    body: [
      h("The rules"),
      table(["Item", "Rule", "9.1 note"],
        ["Interest on unpaid VAT", "1 % a month or part of a month from the due date, at most 24 months (§127)", "41"],
        ["Interest on unpaid SD", "Same rate, on the unpaid SD", "42"],
        ["Late-return penalty", "When the return is filed after the due date — up to Tk 10,000 for a VAT-registered person, set by the officer (§85)", "43"],
      ),
      p("The return and the tax are due 15 days after the end of the month (20 for the extended category), moved to the next working day when that is a weekend or holiday. Rates and amounts come from the effective-dated rules table, so a Finance Act change is a data change."),
      h("The calculator"),
      steps(
        "Open the [compliance centre](/vat/mushak) and pick the tax period.",
        "**Interest & penalty** starts from the period's return: the tax still unpaid and the filing date.",
        "Change the payment date, the filing date or the amounts to see what a later payment would cost; months are counted from the due date, a started month counts in full.",
        "Use the buttons to open the 9.1 return (notes 41–44) or to deposit the interest or penalty with a TR-6 challan.",
      ),
      p("Below the calculator, **Exposure** lists every period that owes interest or a penalty today."),
      note("This is an estimate from the return figures. The penalty amount is decided by the VAT officer — enter the amount in the order once you receive it."),
      tip("Related: [Mushak 9.1 return](help:vat-return-9-1), [Treasury deposits (TR-6)](help:treasury-tr6), [Compliance centre](help:compliance-centre)."),
    ],
  },
  "backup-restore": {
    title: "Restoring a backup and the restore drill",
    summary: "How a backup is restored into a database, what is checked, and the drill that proves the backups can actually be restored.",
    keywords: ["backup", "restore", "drill", "disaster recovery", "recovery", "rpo", "rto", "database", "go 16", "sha-256", "checksum"],
    body: [
      h("Why a drill"),
      p("NBR's General Order 16/Mushak/2019 asks enlisted VAT software for at least two backups a day. A backup only helps if it can be restored, so DiziVAT restores one regularly into an empty database and checks it. The result is shown on [Backups](/master/backups) as **Last restore drill**."),
      h("What the restore does"),
      list(
        "Reads the backup and checks its **SHA-256** against the value recorded when it was taken.",
        "Creates the tables in the new database and loads every table in one transaction.",
        "Compares each table's row count and every document collection with the backup, and verifies the **audit chain** end to end.",
        "Optionally starts the app on the restored database, signs in and lists the sales invoices.",
      ),
      warn("Password hashes are never stored in a backup and sessions are not restored. After a restore everyone is signed out: the administrator signs in with the password given to the restore and resets the other accounts."),
      h("Running a restore (IT)"),
      p("On the server: `node api/dist/restore.js --source <database or .json.gz file> --target <new empty database> --create --admin-password <new password> --boot`. Add `--drop-after --record` for a drill. The full procedure, with recovery-time and data-loss targets, is in docs/BACKUP_RESTORE.md."),
      tip("Related: [Backups and data import](help:backups-and-data-import), [Audit trail](help:audit-log)."),
    ],
  },
} satisfies Record<string, ArticleText>
