import type { ArticleText } from "../types"
import { h, list, note, p, steps, table, tip, warn } from "../blocks"

/** R6.6 articles: export proceeds from the bank PRC file, Mushak 9.3 late filing, Mushak 9.4 amended return. */
export default {
  "export-proceeds-prc": {
    title: "Export proceeds and the bank PRC file",
    summary: "Import the bank's realisation (PRC) file, match each PRC to its export invoices, and follow what is still to realise within 120 days of shipment.",
    keywords: ["prc", "proceeds realisation certificate", "export proceeds", "realisation", "repatriation", "bank file", "exp", "exp form", "lc", "120 days", "overdue", "ageing", "fifo", "rmg", "export"],
    body: [
      h("Why proceeds matter"),
      p("Bangladesh Bank requires the proceeds of every export to be repatriated within **120 days (4 months) of shipment**. When the money arrives, the AD bank credits it and issues a **Proceeds Realisation Certificate (PRC)**. Drawback claims and UD settlement are made on the PRCs, so DiziVAT warns where an export is still unrealised."),
      h("Importing the bank file"),
      steps(
        "Open [Export proceeds](/vat/proceeds) and choose the **Import bank file** tab.",
        "Choose the CSV or Excel export of the bank's PRC / realisation report (or **Try a sample file**). The headings of the [template](/vat/proceeds) are recognised, as are common bank names for them — Value date, PRC No, Ccy, Amount, EXP No, LC No, Invoice No.",
        "DiziVAT proposes a match for every row. Check the rows **to review**, pick or adjust invoices, and tick them.",
        "Choose **Post realisations**. One **bank file** (PB-…) is created, and each invoice shows its PRC under Export proceeds.",
      ),
      h("How rows are matched"),
      table(["Order", "Matched by", "Notes"],
        ["1", "EXP number", "The 11-digit EXP form number on the invoice"],
        ["2", "Invoice number", "As quoted by the bank"],
        ["3", "LC / contract number", "Spread over the LC's open invoices, oldest first (FIFO)"],
        ["4", "Exact amount", "Only when one open invoice in that currency has exactly that outstanding"],
      ),
      list(
        "A PRC can cover several invoices, and an invoice can be realised over several PRCs.",
        "A small short-payment (bank charges) leaves the invoice **part-realised**.",
        "PRCs already recorded, invalid rows and rows in the wrong currency are skipped.",
      ),
      h("Outstanding and ageing"),
      p("The **Outstanding** tab lists every export with proceeds open, its *realise by* date and days left, grouped as past the limit, due within 30 days, 31–60 days and later. Download it as CSV for the bank follow-up."),
      warn("Unrealised exports appear on drawback claims and in UD settlement as a warning: DEDO pays drawback only on realised exports, and the Bond Commissionerate settles a UD on the export documents, PRCs included."),
      note("A bank file posted in error can be **reversed** by an approver: its realisations are removed, and the file stays on record with the reason."),
      tip("Related: [Exports and UDs](help:rmg-exports-and-uds), [Drawback claims](help:drawback-claims), [UD settlement](help:ud-settlement)."),
    ],
  },
  "late-filing-9-3": {
    title: "Late filing permission (Mushak 9.3)",
    summary: "Apply within 7 days after the tax period for up to one more month to file the return. If approved, the late-return penalty is waived, but interest still runs.",
    keywords: ["mushak 9.3", "9.3", "late return", "late filing", "extension", "section 65", "rule 48", "deemed approved", "penalty", "interest", "commissioner", "return applications"],
    body: [
      h("The rule"),
      p("Section 65 of the VAT & SD Act 2012 (rule 48(1)) lets a registered person ask the Commissioner for more time to submit the return:"),
      list(
        "Apply on **Mushak 9.3** within **7 days after the tax period ends** (e.g. by 7 October for September).",
        "The extension is at most **one month from the due date** (the 15th of the following month).",
        "The Commissioner decides within **7 days**; with no decision the application is **deemed approved**.",
        "Permission waives the **late-return penalty** (note 43) up to the allowed date. **Interest** (notes 41 / 42, §127, 1 % a month) still runs from the original due date, because the payment date does not move.",
        "Without permission, a late return attracts the penalty plus interest.",
      ),
      h("In DiziVAT"),
      steps(
        "Open [Return applications](/vat/return-applications) → **Late filing (9.3)** → **New 9.3 application**, or use the link on the return page of the period.",
        "Choose the period, the date you need (after the due date, at most one month later) and the reason. Save the draft.",
        "Print or download the **Mushak 9.3** form, submit it, then **Mark as filed** with the date and reference.",
        "Record the Commissioner's **approval** (with the date allowed) or **refusal**. If nothing is recorded within 7 days of filing, it shows as **Deemed approved**.",
      ),
      table(["Status", "Effect"],
        ["Draft / Awaiting decision", "No effect yet — the due date applies"],
        ["Approved / Deemed approved", "Period stays open up to the allowed date; no late-return penalty in the penalty calculator"],
        ["Refused", "Penalty and interest as for any late return; a new application can be made while the window is open"],
      ),
      note("Only one open application per period. The return itself is still filed as **type B — late return (section 65)**."),
      tip("Related: [Interest and penalties](help:interest-and-penalties), [VAT return (Mushak 9.1)](help:vat-return-9-1), [Amended return (Mushak 9.4)](help:amended-return-9-4)."),
    ],
  },
  "amended-return-9-4": {
    title: "Amended return (Mushak 9.4)",
    summary: "Correct a submitted return within 4 years. Extra tax is paid with interest and no penalty; a decrease needs the Commissioner's decision (deemed after 30 days) and becomes a decreasing adjustment.",
    keywords: ["mushak 9.4", "9.4", "amended return", "amendment", "section 66", "rule 49", "type c", "correction", "clerical error", "decreasing adjustment", "interest", "return applications"],
    body: [
      h("When an amendment is allowed"),
      list(
        "For a **submitted** return, within **4 years** of its submission.",
        "For clerical or computational errors, tax under-declared, tax over-declared or another error or omission (not forgery).",
        "**Not** once a VAT audit, investigation or enquiry has started, or once a VAT officer has found the error.",
        "**Not** to take an input credit or decreasing adjustment whose time limit has already passed.",
      ),
      h("Increase or decrease"),
      table(["Net tax", "What happens"],
        ["Increases", "Deposit the difference with interest (§127) from the original due date to the deposit date, then file the amended return. No penalty."],
        ["Decreases", "The Commissioner decides within 30 days — otherwise it is deemed approved — and allows a decreasing adjustment in a later tax period (VAT note 32, SD note 39)."],
      ),
      h("In DiziVAT"),
      steps(
        "Open [Return applications](/vat/return-applications) → **Amendment (9.4)** → **New 9.4 application**, or use **Apply to amend** on a submitted return.",
        "Choose the period and the reason, describe the error, and add one line per Mushak 9.1 figure to correct (note, column, correct figure, explanation). The figure as filed is shown alongside.",
        "Tick the declaration that no audit or enquiry has started, and save the draft. The effect on net VAT / SD — and, for an increase, the interest to date — is worked out at once.",
        "Print the **Mushak 9.4** form, submit it and **Mark as filed**. Record the Commissioner's approval or refusal (for a decrease: the period of the adjustment).",
        "Choose **File amended return**. For an increase, enter the treasury challan; the deposit must cover the difference plus interest to the deposit date. For a decrease, an approved decreasing adjustment is posted in the allowed period.",
      ),
      note("The amended figures become the base for any further amendment of the same period (amendment no. 2, 3 …). The original return stays locked."),
      warn("A decreasing adjustment needs a later period whose return is not yet submitted."),
      tip("Related: [Late filing (Mushak 9.3)](help:late-filing-9-3), [VAT adjustments](help:vat-adjustments), [VAT return (Mushak 9.1)](help:vat-return-9-1)."),
    ],
  },
} satisfies Record<string, ArticleText>
