import type { ArticleText } from "../types"
import { h, list, note, p, steps, table, tip, warn } from "../blocks"

export default {
  "sales-invoices": {
    title: "Sales invoices and Mushak 6.3",
    summary: "Issue a tax invoice for goods, approve it, print the Mushak 6.3 and follow up payment.",
    keywords: ["invoice", "challan", "6.3", "mushak 6.3", "tax invoice", "sale", "sell", "customer", "vat", "sd", "supplementary duty", "approve", "print", "fifo", "batch"],
    body: [
      h("Before you start"),
      list(
        "The **customer** must exist in [Customers](/master/customers) with a valid 13-digit BIN (foreign customers use a reference instead).",
        "Each product must be an **item** with an HS code, VAT rate and, where applicable, an SD rate. See [Items, HS codes and units](help:items-and-hs-codes).",
        "There must be enough stock at the branch the goods leave from, or you can only save a draft.",
      ),
      h("Create an invoice"),
      steps(
        "Go to [Sales invoices](/sales) and click **New invoice**, or press {{N}}.",
        "Under **Customer & delivery**, pick the customer. BIN and address fill in. The **Delivery address** defaults to the customer's address. **Vehicle type & no.** is required for goods in transit.",
        "Choose the **Branch / warehouse** the goods leave from.",
        "Under **Items**, pick each product and enter **Qty** and **Unit price**. The form shows stock *In stock* at that branch and warns if a quantity exceeds it. If the product is batch-tracked, choose a **Batch** or leave *Any batch (FIFO)*.",
        "Check the SD % and VAT % per line. They come from the item and can be adjusted if a line is taxed differently.",
        "Enter **Discount**, the **Payment method** (Bank, Cash, Cheque, Mobile banking or LC / TT) and any amount **Received** now.",
        "Tick **VDS applicable** if the buyer deducts VAT at source. It is pre-ticked for customers known to withhold.",
        "Fill in the **Authorised person** (name and designation printed on the 6.3).",
        "Click **Save & approve** ({{Ctrl+Enter}}), or **Save as draft** to finish later or leave it for an approver.",
      ),
      h("How the tax is calculated"),
      table(["Figure", "Formula"],
        ["Value", "Qty × Unit price"],
        ["SD", "Value × SD %"],
        ["VAT", "(Value + SD) × VAT %"],
        ["Net total", "Value + SD + VAT − Discount"],
        ["Due", "Net total − Received (and later receipts or VDS)"],
      ),
      p("All figures are rounded to 2 decimals per line. The **Summary** panel shows the totals as you type."),
      tip("If the customer has a **credit limit**, the form shows receivable, overdue and available credit, and warns before an invoice goes over the limit."),
      h("Approve, print and share"),
      p("Approving moves stock out of the branch and includes the invoice in this period's [Mushak 6.2 sales book](help:purchase-sales-books) and [9.1 return](help:vat-return-9-1). Approvers can approve drafts from the invoice page, or several at once by ticking them in the list and choosing **Approve** in the bulk bar."),
      p("Open an invoice to see its **Overview**, the **Mushak 6.3 preview**, any **Credit notes** and its **History**. Click **Print Mushak 6.3** and choose a printer or *Save as PDF*. The layout follows the official bilingual form on A4."),
      h("Correcting an invoice"),
      list(
        "**Drafts** can be edited or deleted. Delete offers **Undo** for a few seconds.",
        "**Approved** invoices cannot be edited. Click **Cancel invoice**, give a reason (common reasons are one click away) and issue a new invoice. Cancelling returns the stock and removes the invoice from the return.",
        "If the goods were delivered and some came back, don't cancel. Issue a [credit note](help:credit-notes) instead.",
      ),
      warn("Once the period's 9.1 return is submitted, its invoices can't be cancelled or changed. Record corrections in the open period with a credit note or a [VAT adjustment](help:vat-adjustments)."),
      h("Following up payment"),
      p("The **Payment** filter shows *Paid*, *Partly paid* and *Unpaid* invoices, and the **Unpaid & partly paid** view lists what is still due. Record money received under [Receipts](help:receipts-and-payments). When a customer withholds VAT, record their certificate under [VDS](help:vds-certificates); it reduces the due as well."),
    ],
  },

  "service-sales": {
    title: "Service sales",
    summary: "Invoice services such as job work, cylinders or design on Mushak 6.3, with no stock movement.",
    keywords: ["service", "job work", "cylinder", "design", "service code", "6.3", "vds", "service sale"],
    body: [
      h("When to use it"),
      p("Use [Service sales](/sales/services) for supplies that are not goods from stock, for example job work, printing cylinders or artwork. They print on the same Mushak 6.3 but move no stock and carry no SD."),
      h("Create a service sale"),
      steps(
        "Open [Service sales](/sales/services) and click **New service sale**.",
        "Pick the customer and branch, as for a goods invoice.",
        "For each line, choose the **service code** (search by name or code), then enter quantity and price. VAT uses the rate of that service; SD does not apply.",
        "Tick **VDS applicable** if the buyer withholds VAT. Many service buyers must.",
        "**Save & approve**, or **Save as draft**.",
      ),
      p("Service sales have their own list and numbers starting with **SS-**. They count in the 9.1 return like any other sale at their rate."),
      tip("If the customer withholds VAT, ask for their **Mushak 6.6** certificate and record it under [VDS](help:vds-certificates). The invoice due then drops by the withheld VAT."),
    ],
  },

  "exports": {
    title: "Export sales (direct and deemed)",
    summary: "Zero-rated invoices to foreign buyers, or to local export-oriented units against a back-to-back LC.",
    keywords: ["export", "deemed export", "zero rated", "0%", "lc", "letter of credit", "back to back", "bill of export", "customs", "foreign customer"],
    body: [
      h("Two kinds of export"),
      table(["", "Direct export", "Deemed export"],
        ["Customer", "**Foreign** customer", "**Local** (BIN-registered) export-oriented unit"],
        ["Documents", "LC, customs house, destination, Bill of Export", "Back-to-back LC"],
        ["VAT", "0% (zero-rated)", "0% (zero-rated)"],
        ["9.1 note", "Note 1", "Note 2"],
      ),
      h("Create an export invoice"),
      steps(
        "Open [Export sales](/sales/exports) and click **New export invoice**.",
        "Pick the customer. For a **foreign** customer the **Export documents** section opens: enter **LC no.** and **LC date**, **Customs house**, **Destination country**, **Bill of Export no.** and **date**, **Shipping address** and **C&F agent**.",
        "For a **deemed export**, pick the local customer and tick **Deemed export (back-to-back LC)**, then enter the LC details.",
        "Add the items. VAT is set to 0% automatically and SD does not apply.",
        "**Save & approve**. Stock leaves the branch as with any sale.",
      ),
      h("Checks DiziVAT makes"),
      list(
        "A direct export must go to a foreign customer, and a deemed export to a local one.",
        "Export documents are required for a foreign customer.",
        "The LC date cannot be after the invoice date.",
      ),
      tip("Zero-rated sales still let you claim input tax credit on the materials used. Keep your purchase records complete; see [Local and import purchases](help:local-purchases)."),
      note("The **Export sales** quick view in [Sales invoices](/sales) lists exports next to your local sales."),
    ],
  },

  "credit-notes": {
    title: "Credit notes (Mushak 6.7)",
    summary: "Record goods returned by a customer against an approved invoice. This restores stock and reduces output tax.",
    keywords: ["credit note", "6.7", "mushak 6.7", "sales return", "return", "customer return", "refund", "reduce vat", "note 31"],
    body: [
      h("When to issue a credit note"),
      p("Issue a credit note when a customer returns goods after an approved invoice, for example damaged in transit, a quality complaint, excess supply, the wrong item or a price adjustment. The original invoice stays as it is; the credit note reverses the returned share."),
      h("Issue a credit note"),
      steps(
        "Open [Credit notes](/sales/credit-notes) and click **Issue credit note**, or use the **Credit notes** tab on the invoice.",
        "Choose the **Sales invoice**. Only approved goods invoices with quantity left to return are offered.",
        "For each line, enter the **Return qty**. The form shows what was sold, already returned and left. The value, SD and VAT are the returned share at the invoiced price and rates.",
        "Choose a **Reason**, add a **Note** and fill in the responsible person.",
        "**Save & approve**, or **Save draft**.",
      ),
      h("What approval does"),
      list(
        "Returned goods go back into stock at the invoice's branch.",
        "Output tax falls in the return: VAT in **note 31** and SD in **note 39** of Mushak 9.1.",
        "The invoice's due is reduced.",
      ),
      p("Open the note and click **Print 6.7** to print the official credit note for the customer."),
      warn("You cannot return more than is left on the invoice, and the credit note cannot be dated before the sale. If the original invoice was wrong rather than returned, cancel it instead (while its period is open)."),
    ],
  },
} satisfies Record<string, ArticleText>
